version: "3"
services:
    cloudapper.api:
        image: social-network-api:v1.1.0.5
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:80"
        depends_on:
            - "db"
    db:
        image: "mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04"
        environment:
            SA_PASSWORD: "qwertY12@3"
            ACCEPT_EULA: "Y"
        ports: 
            - "1433:1433"
        volumes:
            - sql_data_volume:/var/opt/mssql
volumes: 
    sql_data_volume: